name: Visual Tests

# all pull requests
on: pull_request

jobs:
  visual-tests:
    name: Polymer 2 on SauceLabs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Install global npm dependencies
        # bower is needed to run 'bower install'
        # gemini is needed to run the visual tests step
        run: "npm install --quiet --no-progress --global bower gemini@^4.0.0 gemini-sauce gemini-polyserve"

      - name: Install project npm dependencies
        run: "npm ci"

      - name: Install project Bower dependencies
        run: "bower install --quiet"

      - name: Run visual tests on SauceLabs
        run: "gemini test --reporter html --reporter flat test/visual"
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Publish the Visual Tests failures report as an Artifact for this Workflow run
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Visual tests failures report
          path: gemini-report/
